# **Obtención y preparación de datos**
# OPD04. Operaciones con Array

In [2]:
import numpy as np

## <font color='blue'>**Ordenar y agregar elementos a un arreglo**</font>

Ordenar un elemento es simple con `np.sort()`. Puede especificar el eje, el tipo y el orden cuando llama a la función.

In [3]:
arr = np.array([2, 1, 5, 10, 3, 7, 4, 9, 6, 8])
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
b.shape

(4,)

Para agregar elementos, se utiliza la función `np.concatenate()`:

In [6]:
c = np.concatenate((a, b))
print(c)


[1 2 3 4 5 6 7 8]


In [7]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [9]:
print(x)
print()
print(y)
print()
r =np.concatenate((x, y), axis=0)
print(r)

[[1 2]
 [3 4]]

[[5 6]]

[[1 2]
 [3 4]
 [5 6]]


## <font color='blue'>**Forma y Tamaño de un Arreglo**</font>

`ndarray.ndim` entrega el número de ejes, o dimensiones, del arreglo.

`ndarray.size` entrega el número total de elementos del arreglo.

`ndarray.shape` entrega una tupla de números enteros que indican el número de elementos almacenados a lo largo de cada dimensión del arreglo. Si, por ejemplo, 

tiene un arreglo 2D con 2 filas y 3 columnas, la forma de su arreglo es (2, 3).

Por ejemplo:

In [10]:
arr_ejemplo = np.array([[[0, 1, 2, 3],[4, 5, 6, 7]],
                        [[0, 1, 2, 3],[4, 5, 6, 7]],
                        [[0 ,1 ,2, 3],[4, 5, 6, 7]]])
arr_ejemplo

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [11]:
arr_ejemplo.ndim

3

In [ ]:
arr_ejemplo.size

In [ ]:
arr_ejemplo.shape

## <font color='blue'>**Redimensionamiento de Arreglos**</font>

El método de `reshape()` le dará una nueva forma a un arreglo sin cambiar los datos. Recuerde que cuando usa el método de redimensionamiento, el arreglo que desea generar debe tener la misma cantidad de elementos que el arreglo original. Si comienza con un arreglo con 12 elementos, deberá asegurarse de que su nueva arreglo también tenga un total de 12 elementos.

In [ ]:
a = np.arange(6)
print(a)
a.shape

In [ ]:
b = a.reshape(3, 2)
print(b)
b.shape

## <font color='blue'>**Transponer un Arreglo**</font>

In [ ]:
arr = np.arange(6).reshape((2, 3))
arr

In [ ]:
arr.transpose()

## <font color='blue'>**¿Cómo agregar nuevos ejes (dimensiones) a un arreglo?**</font>

Con las funcionaes `np.newaxis` y `np.expand_dims` se puede aumentar las dimensiones de su arreglo existente.

El uso de `np.newaxis` aumentará las dimensiones de su arreglo en una dimensión cuando se use una vez. Esto significa que una arreglo 1D se convertirá en una arreglo 2D, una arreglo 2D se convertirá en una arreglo 3D, y así sucesivamente. Por ejemplo:

In [12]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
print(a)
a.shape

[1 2 3 4 5 6 7]


(7,)

In [13]:
a2 = a[np.newaxis, :]
print(a2)
a2.shape

[[1 2 3 4 5 6 7]]


(1, 7)

Es posible convertir explícitamente un arreglo 1D a un vector de fila o a un vector de columna usando `np.newaxis`. Por ejemplo, puede convertir un arreglo 1D en un vector de fila insertando un eje a lo largo de la primera dimensión:

In [ ]:
row_vector = a[np.newaxis, :]
print(row_vector)
row_vector.shape

o convertirlo en un vector columna, insertando un eje en la segunda dimensión:

In [ ]:
col_vector = a[:, np.newaxis]
print(col_vector)
col_vector.shape

También es posible expandir un arreglo insertando un nuevo eje en una posición específica con la función `np.expand_dims()`:

In [14]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [15]:
b = np.expand_dims(a, axis=1)
print(b.shape)
b

(6, 1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
c = np.expand_dims(a, axis=0)
print(c.shape)
c

## <font color='green'>**Actividad 1**</font>

Crear un arreglo bidimensional _A_ de 5x5 con todos los valores cero. Usando el indexado de matrices, asignar 1 a todos los elementos de la última fila y 5 a todos los elementos de la primera columna. Finalmente, asignar el valor 100 a todos los elementos de la subarreglo central de 3x3 de la arreglo de 5x5.


In [46]:
arr= np.zeros((5,5))
print(arr)
for filas in arr:
    filas[0] += 5
print(arr)

for x in range(len(arr)):
    arr[4][x]+=1
    for y in range(len(arr)):
        if x > 0 and y > 0 and x < 4 and y < 4:
            arr[x][y] += 100
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[5. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0.]]
[[  5.   0.   0.   0.   0.]
 [  5. 100. 100. 100.   0.]
 [  5. 100. 100. 100.   0.]
 [  5. 100. 100. 100.   0.]
 [  6.   1.   1.   1.   1.]]


<font color='green'>**Fin actividad 1**</font>

## <font color='blue'>**Elementos únicos y conteo**</font>

In [48]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
valores_unicos = np.unique(a)
print(valores_unicos)

[11 12 13 14 15 16 17 18 19 20]


Para obtener los índices de los valores únicos en un arreglo NumPy se debe usar el argumento `return_index` en la función `np.unique()`:

In [49]:
valores_unicos, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


Puede pasar el argumento `return_counts` en `np.unique()` junto con su arreglo para obtener el recuento de frecuencia de valores únicos en un arreglo de NumPy:

In [50]:
valores_unicos, contar_ocurrencia = np.unique(a, return_counts=True)
print(contar_ocurrencia)

[3 2 2 2 1 1 1 1 1 1]


## <font color='blue'>**Aplicar una función sobre una fila o columna de un arreglo**</font>

La función `np.apply_along_axis()` permite aplicar una función sobre una de las dimisiones de un arreglo. Por lo que es una herramienta con muchas posibilidades. La función tiene tres parámetros, en el primero se indica la función que se desea aplicar, en la segunda el eje sobre el que se desea aplicar la función y finalmente el arreglo. Obteniéndose como salida de la función un arreglo con un eje menos que el original.

Por ejemplo:

In [51]:
arr = np.arange(1, 10).reshape(3,3)
print(arr)
np.apply_along_axis(sum, 0, arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [ ]:
# Función que calcula el promedio entre el primero y el último elemento de un vector
def my_func(a):
    return (a[0] + a[-1]) * 0.5

b = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(b)
np.apply_along_axis(my_func, 0, b)

In [ ]:
np.apply_along_axis(my_func, 1, b)

## <font color='green'>**Actividad 2**</font>

Los diámetros de las esporas del _lycopodium_ pueden medirse por métodos interferométricos &#129299; &#129299; &#129299;. Los resultados de uno de estos experimentos son los siguientes:

<img src='esporas.png' width="600" align="center" style="margin-right: 50px">

donde $k$ = 5880.

Calcular, usando funciones de NumPy, el diámetro medio de las esporas y la desviación estándar de la muestra. Separar, en matrices independientes, las medidas de los diámetros:

* Que tengan valores inferiores a la media ($\mu$) menos la desviación estándar ($\sigma$), es decir $d < \mu_{d} - \sigma_{d}$
* Que tengan valores superiores a la media más la desviación estándar, es decir $d > \mu_{d} + \sigma_{d}$
* Que tengan valores entre $\mu_{d} - \sigma_{d} < d < \mu_{d} + \sigma_{d}$

*Fuente: Adaptado de Curso de Computación Científica, J. Pérez, T. Roca y C. López*

In [2]:
# Tu código aquí ...

# A partir de la tabla entregada, creamos una martix
esporas = np.array([[14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
                    [1, 1, 8, 24, 48, 58, 35, 16, 8, 1]])

print(esporas.shape, '\n')
# Creamos una matriz de ceros con la cantidad total de esporas
mat_tot = np.zeros(sum(esporas[1]))
# Instanciamos tres listas vacias para recolectar resultados
mat_menos_media = []
mat_mas_media = []
mat_media = []
# Creamos un indice para las listas
ind = 0

# Creamos una función para construir nuestro vector de diámetros 
def my_func(a):
    global ind
    # Sumamos el diámetro de cada espora tantas veces como fue observado
    for i in range(a[1]):
        mat_tot[ind] = a[0]
        ind += 1

# Aplicamos nuestra función por filas (axis=0)
np.apply_along_axis(my_func, 0, esporas)
print(mat_tot, '\n')
print(f'Media = {np.mean(mat_tot)}\n')
print(f'Desviación estándar = {np.std(mat_tot)}\n')

# Creamos una función para clasificar los diámetros segun su marnitud
def my_func2(a):    
    if a[0] > np.mean(mat_tot) + np.std(mat_tot):
        mat_mas_media.append(a[0])
    elif a[0] < np.mean(mat_tot) - np.std(mat_tot):
        mat_menos_media.append(a[0])
    else:
        mat_media.append(a[0])

# La aplicamos
np.apply_along_axis(my_func2, 0, esporas)

# Convertimos las listas en arrays Numpy
mat_mas_media = np.array(mat_mas_media)
mat_media = np.array(mat_media)
mat_menos_media = np.array(mat_menos_media)

print(f'Cantidad esporas con diámetro mayores a media - std: {mat_mas_media}')
print(f'Cantidad esporas con diámetro entre a media +/- std: {mat_media}')
print(f'Cantidad esporas con diámetro menores a media - std: {mat_menos_media}')

(2, 10) 

[14. 15. 16. 16. 16. 16. 16. 16. 16. 16. 17. 17. 17. 17. 17. 17. 17. 17.
 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 18. 18.
 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18.
 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18.
 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 19. 19. 19. 19. 19. 19. 19. 19.
 19. 19. 19. 19. 19. 19. 19. 19. 19. 19. 19. 19. 19. 19. 19. 19. 19. 19.
 19. 19. 19. 19. 19. 19. 19. 19. 19. 19. 19. 19. 19. 19. 19. 19. 19. 19.
 19. 19. 19. 19. 19. 19. 19. 19. 19. 19. 19. 19. 19. 19. 20. 20. 20. 20.
 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20.
 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 21. 21. 21. 21. 21.
 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 22. 22. 22. 22. 22. 22. 22.
 22. 23.] 

Media = 18.83

Desviación estándar = 1.4802364675956337

Cantidad esporas con diámetro mayores a media - std: [21 22 23]
Cantidad esporas con diámetro entre a media +/- std: [

<font color='green'>**Fin actividad 2**</font>